# Generated by Django 4.2.6 on 2024-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('count_orders', models.IntegerField(verbose_name='Количество заказов')),
                ('date_of_registration', models.DateTimeField(verbose_name='Дата регистрации на сервисе')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
