# Generated by Django 4.2.6 on 2024-04-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('type', models.CharField(max_length=11, verbose_name='Тип техники')),
                ('description', models.CharField(max_length=11, verbose_name='Описание')),
                ('rating', models.CharField(max_length=11, verbose_name='Рейтинг')),
                ('year_of_production', models.CharField(max_length=11, verbose_name='Год выпуска')),
                ('timetable', models.CharField(max_length=11, verbose_name='Бронирование')),
                ('count_jobs_done', models.IntegerField(verbose_name='Количество выполненых заказов')),
                ('date_of_registration', models.DateTimeField(verbose_name='Дата регистрации на сервисе')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
            },
        ),
    ]
