# Generated by Django 4.2.6 on 2024-04-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='FIO',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='timetable',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=1, max_length=50, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_production',
            field=models.CharField(max_length=4, verbose_name='Год выпуска'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
