# Generated by Django 4.2.6 on 2024-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehicle_fio_remove_vehicle_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='postimage',
            name='images',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
