# Generated by Django 4.2.6 on 2024-04-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback_owner',
            options={'verbose_name': 'Отзыв_о_владельце', 'verbose_name_plural': 'Отзывы_о_владельце'},
        ),
    ]
